### ISSUE TITLE
the_prprocessed_data

### ISSUE THREAD

**Issue by THE-SINDOL** [Grace9994/CoMoSVC#3]
i have a little errors when i launch : 
python preprocessing2_flist.py
 67%|███████████████████████████████████████████████████████▎                           | 2/3 [00:00<00:00, 282.36it/s]
Traceback (most recent call last):
  File "preprocessing2_flist.py", line 46, in <module>
    for file_name in os.listdir(os.path.join(args.source_dir, speaker)):
NotADirectoryError: [WinError 267] Nom de répertoire non valide: './dataset\\the_prprocessed_data'

and there a empty file call the_prprocessed_data need to be dataset folder, but need to copy on \dataset\YOURNAME\

**Comment by dillfrescott** [comment]
Delete that placeholder file and it should work

**Comment by Grace9994** [comment]
> Delete that placeholder file and it should work

**Comment by Andrew-moon** [comment]
Very useful, thanks!
